# Generated by Django 3.2.10 on 2023-05-24 15:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LabelModel',
            fields=[
                ('label_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label_name', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TestModel',
            fields=[
                ('test_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('test_title', models.CharField(max_length=50)),
                ('test_format', models.IntegerField(choices=[(2, '2択問題'), (4, '4択問題')])),
                ('test_keyword', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('public_key', models.BooleanField(default=True)),
                ('score', models.CharField(default='0/3', max_length=50)),
                ('label', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='createst.labelmodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProblemModel',
            fields=[
                ('problem_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('problem_statement', models.CharField(max_length=200)),
                ('correct_answer', models.CharField(max_length=50)),
                ('user_answer', models.CharField(blank=True, max_length=50, null=True)),
                ('is_correct', models.BooleanField(blank=True, default=None, null=True)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='createst.testmodel')),
            ],
        ),
        migrations.CreateModel(
            name='ChoiceModel',
            fields=[
                ('choice_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('choice', models.CharField(max_length=50)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='createst.problemmodel')),
            ],
        ),
    ]
